### ISSUE TITLE
Additional option / feature request

### ISSUE THREAD

**Issue by ernestgwilsonii** [crossorigin/node-slack-upload#4]
Can you please allow for a way to upload "content" in addition to what you have now "file"?
Looking at:
https://api.slack.com/methods/files.upload
It looks like the API offers two methods:
file
or
content
In many cases, we already have a bunch on data stored in a variable and we'd like to upload that as nicely formatted "text" attachment type using "content" and currently this module makes us write to disk so we can read from "file"
Could you you please consider adding a variation that includes / allows us to use something like:
content: contents
instead of:
file: fs.createReadStream(path.join(__dirname, '..', 'README.md')),

**Comment by idosh** [comment]
Can you try making a PR?

**Comment by idosh** [comment]
Closed by #5
